add TeacherController
Progi-Petrovi/triolingo pull request #19
Opened 2024-11-07 17:42 UTC by skledaar

add TeacherController and all the methods in TeacherService and TeacherRepository needed for it to work
change JpaRepository ID type in TeacherRepository from Integer to Long

2024-11-07 17:48 UTC, stjepanbonic commented on backend/src/main/java/com/triolingo/controller/TeacherController.java
> +    @Autowired
let's do constructor injection instead of field injection, you can delete this annotation and generate constructor instead

2024-11-07 17:48 UTC, stjepanbonic commented on backend/src/main/java/com/triolingo/service/TeacherService.java
> +    @Autowired
same here, constructor injection instead of field

2024-11-07 17:50 UTC, stjepanbonic commented on backend/src/main/java/com/triolingo/service/TeacherService.java
> +    public Teacher updateTeacher(Teacher teacher) {
instead of asserting not null in method, use @NotNull annotation before of Teacher teacher

2024-11-07 17:52 UTC, stjepanbonic commented on backend/src/main/java/com/triolingo/service/TeacherService.java
> +        Assert.isTrue(teacherRepository.existsById(teacher.getId()), "Teacher doesn't exist");
let's do a simple if instead, we can later catch exceptions with ControllerAdvice

2024-11-07 17:59 UTC, LeoTheMoldyLemon commented on backend/src/main/java/com/triolingo/controller/TeacherController.java
> +    public ResponseEntity<Teacher> createTeacher(@RequestBody Teacher teacher) {
Having the request body be an entity object is a big no no, create a DTO instead

2024-11-07 18:01 UTC, stjepanbonic commented on backend/src/main/java/com/triolingo/service/TeacherService.java
> +    public List<Teacher> listAll() {
generally, service is used to encapsulate any logic that couldn't be done with just repo, so this is kind of a uneeded bit of code, it's prefectly fine to have repository inside of controller, as long as any bigger logic is handled with service

2024-11-07 18:01 UTC, LeoTheMoldyLemon commented on backend/src/main/java/com/triolingo/service/TeacherService.java
> +        Assert.notNull(teacher, "Teacher isn't provided");
using assert on public method parameters, outside of unit test is very bad practice, generate an actual exception or add a \@NotNull tag to the parameter.

2024-11-07 18:05 UTC, stjepanbonic requested changes
good work! nice first pr, just a couple things to solve, keep it up :D

2024-11-07 18:14 UTC, stjepanbonic commented on backend/src/main/java/com/triolingo/service/TeacherService.java
> +        teacherRepository.delete(teacher);
There is also deleteById method

2024-11-09 15:15 UTC, skledaar commented on backend/src/main/java/com/triolingo/service/TeacherService.java
> +        Assert.isTrue(teacherRepository.existsById(teacher.getId()), "Teacher doesn't exist");
and if it doesn't work, return null? is it good practice to have a "return null;" outside of the if, or should i put it into the else?

2024-11-09 15:40 UTC, skledaar commented on backend/src/main/java/com/triolingo/controller/TeacherController.java
> +    public ResponseEntity<Teacher> createTeacher(@RequestBody Teacher teacher) {
I don't exactly understand what all needs to be changed. To create a teacher, don't we need to send all fields? So the DTO would have all the same the same as teacher? Should i just leave this, as you said you were working on the DTO?

2024-11-09 15:47 UTC, skledaar commented on backend/src/main/java/com/triolingo/service/TeacherService.java
> +    public List<Teacher> listAll() {
Okay, the service was already there so I worked with it, following what they did in the lectures. So we could declare both a repo and a service in the contoller? Or omit the service if it isn't needed?

2024-11-10 11:05 UTC, stjepanbonic commented on backend/src/main/java/com/triolingo/service/TeacherService.java
> +    public List<Teacher> listAll() {
yeah, if there isn't any bigger logic to encapsulate than what repository itself offers, then service is not needed, however this is not such a big deal and if they did it in lectures we can leave it as it is here :+1:

2024-11-10 11:05 UTC, stjepanbonic commented on backend/src/main/java/com/triolingo/service/TeacherService.java
> +        Assert.isTrue(teacherRepository.existsById(teacher.getId()), "Teacher doesn't exist");
if it doesn't work, throw exception, those will be later caught with the ControllerAdvice

2024-11-10 11:42 UTC, stjepanbonic commented on backend/src/main/java/com/triolingo/controller/TeacherController.java
> +@RequestMapping("/teachers")
one additional thing, let's do /api/teachers
I already put /api/languages for LanguageController so we are consistent here, will be easier for frontend side

2024-11-10 20:53 UTC, stjepanbonic approved these changes

2024-11-11 14:59 UTC, merged